### ISSUE TITLE
Have to refresh VS Code folding setting for the extension to work

### ISSUE THREAD

**Issue by AgamlaRage** [zokugun/vscode-explicit-folding#24] opened 2020-08-18 09:33 UTC
VS Code 1.48.0
Explicit Folding 0.8.2

# Issue

When opening **VS Code** the **Explicit Folding** extension seems to not be initialized.

In my case, the extension won't work until I *refresh* the `settings.json` by adding/removing/commenting any **folding setting key**.

GIF explanation:
1. I just started **VS Code** (as I said, **Explicit Folding** is not working yet, you can see it on the `style.scss`)
2. Then I move my cursor to the `settings.json`
3. I comment a line of the **Explicit Folding** configuration
4. Save `settings.json`
5. After few seconds, **VS Code** seems to reinitialized something 
6. **Explicit Folding** is NOW working
7. I uncomment the commented line
8. **Explicit Folding** is STILL working

![screen](https://user-images.githubusercontent.com/15155827/90493783-13d4e800-e143-11ea-804b-db8ea0181760.gif)

# Tests

- Tested with every others extensions disabled, still not working after **VS Code** just started.
- In the step 3 of my GIF explanation, you also can REMOVE or ADD any key to the **Explicit Folding** configuration instead of commenting one, it will have the same result, **Explicit Folding** will work after after that.

# Config

Here is my **Explicit Folding** config in **VS Code** `settings.json`

<details>
<summary>settings.json</summary>

```json
{
  "folding": {
    "javascript": [
      {
        "begin": "/*",
        "end": "*/",
      },
      {
        "begin": "(",
        "end": ")",
      },
      {
        "begin": "[",
        "end": "]",
      },
      {
        "begin": "{",
        "end": "}",
      },
    ],
    "json": [
      {
        "begin": "{",
        "end": "}"
      },
      {
        "begin": "[",
        "end": "]"
      },
    ],
    "php": [
      {
        "begin": "/*",
        "end": "*/",
      },
      {
        "begin": "[",
        "end": "]",
      },
      {
        "begin": "{",
        "end": "}",
      },
    ],
    "css": [
      {
        "begin": "{",
        "end": "}"
      },
    ],
    "scss": [
      {
        "begin": "{",
        "end": "}"
      },
      {
        "begin": "(",
        "end": ")"
      },
    ],
    "html": [
      {
        "beginRegex": "<[a-z]+(>|.*?[^/]>)",
        "endRegex": "<\/[a-z]+>",
      },
    ],
  }
}
```
</details>

**Comment by daiyam** [comment] 2020-08-18 10:26
@AgamlaRage Ya, I can reproduce the issue with VS Code 1.48.0. I will look at what has been changed into VS Code.

**Comment by daiyam** [comment] 2020-08-18 16:09
I can't locate the regression since no code regarding the folding has recently been modified...
You can try my spin of VS Code ([MrCode](https://github.com/zokugun/MrCode)) which doesn't suffer from this issue...

**Comment by AgamlaRage** [comment] 2020-08-18 19:11
@daiyam I have this issue since I installed your extension (~1year).
I don't think the problem comes from a recent change.
I didn't report it because I found this workaround (modifying `settings.json`) that take me only a few seconds when I start VS Code again.

I will take a look to your [MrCode](https://github.com/zokugun/MrCode) for sure!

**Comment by daiyam** [comment] 2020-08-18 21:46
So you had the issue before the updates I've made this spring ?

**Comment by AgamlaRage** [comment] 2020-08-19 18:03
@daiyam Yes, I think so.

**Comment by daiyam** [comment] 2020-08-19 22:10
Wow, I can't believe I've never catch this bug (I've always run a custom build to be able to control the folding...).
I've tested on VS Code 1.36.1 and the bug is there. Damn!
I will try to fix it asap but it might take some time...

**Comment by daiyam** [comment] 2020-08-20 14:29
@AgamlaRage I've found the bug and a fix is on its way. Basically, the registry provides the folding providers in an FILO way. Since the extensions providers are registered before the default ones, you get the issue you are getting. (By editing the config, you are re-registering the providers)
The fastest and sure fix, it's to add a delay on the first registration of the providers... by default, it will be: 1000ms

**Comment by AgamlaRage** [comment] 2020-08-20 15:01
@daiyam Sounds great! Thx for your reactivity.

As an additional idea : **Be able to set a custom delay** using VS Code `settings.json`
(You already seem to had this idea, but just in case).

**Comment by daiyam** [comment] 2020-08-20 15:20
I've already added it: `explicitFolding.startupDelay` :wink:
The new version is up. Tell me if everything is ok.

**Comment by AgamlaRage** [comment] 2020-09-14 08:04
Hello,

it seems to work randomly.
I made two GIF to show you what is happening but I can't find an explanation or a pattern.

**Modifications**
- `activationEvents` is updated inside `%USERPROFILE%\.vscode\extensions\zokugun.explicit-folding-0.9.0\package.json`
- Delay set to 4sec inside VSCode `settings.json` : `"explicitFolding.startupDelay": 4000,`

TEST 1:
- workspace started showing a SCSS file
- SCSS/PHP are folding in 1 line
- JS doesn't fold in 1 line

![screen-not-working-when-starting-vs-code](https://user-images.githubusercontent.com/15155827/93058952-57ead800-f670-11ea-9303-f1e68eed73a0.gif)

TEST 2:
- workspace started showing a PHP file
- PHP is folding in 1 line
- SCSS/JS don't fold in 1 line

![screen](https://user-images.githubusercontent.com/15155827/93059023-7224b600-f670-11ea-9e6f-36bae56f2b42.gif)

---

PS: 
- I had to modified the GIF (cutting some images) to reduce the size BUT **I waited the 4sec delay for the extension to work before doing any actions on VSCode**
- Sorry for the delay of my response, I wasn't available during this period

**Comment by daiyam** [comment] 2020-09-14 08:40
VSCode reloads the extensions when it's viewing a new file type. Keep `explicitFolding.startupDelay` at `1000` and wait just after viewing a new file type.

You should try [MrCode](https://github.com/zokugun/MrCode) which avoids any conflict between folding providers.

**Comment by daiyam** [comment] 2020-12-15 11:29
@AgamlaRage Have you tried [MrCode](https://github.com/zokugun/MrCode)?

**Comment by AgamlaRage** [comment] 2020-12-19 09:16
@daiyam Sorry, no.
I have no time to code at the moment, I also didn't open VSCode in a while (I hope soon).
If you prefer to close the issue, I'll understand.

**Comment by daiyam** [comment] 2021-05-14 01:09
When doing a final review of your issue and still able to reproduce the issue, I've found the solution: using deferred provider. So the real folding provider is always loaded after the language's folding provider which fix the issue. I just wonder why I haven't thought of that solution before...
The fix is in the version `v0.13.0`.

**Comment by AgamlaRage** [comment] 2021-05-15 08:19
@daiyam Hello, since I updated to `v0.13.0` I didn't see this bug again! 🔥 🔥 🔥 

Thank you so much

**Comment by daiyam** [comment] 2021-05-15 11:01
I'm happy that it's finally working but it's a hacky solution. Basically, when the deferred provider is called to provide the folding ranges of a file, for only the first time, it will register of the real provider (with the delay) and will unregister itself.

**Closed** 2021-05-18 10:02 UTC
Labels: bug
