### ISSUE TITLE
Add "explicitFolding.saveFoldsInProject" setting

### ISSUE THREAD

**Issue by PAI5REECHO** [zokugun/vscode-explicit-folding#80] opened 2022-04-25 07:06 UTC
## Describe the feature
Basically I want something like [`"bookmarks.saveBookmarksInProject": true`](https://github.com/alefragnani/vscode-bookmarks#improved-multi-root-support=) but for this extension that way when I close and reopen a project it still has the same folds collapsed

**Comment by daiyam** [comment] 2022-04-25 08:17
@PAI5REECHO Hi, it's a duplicate of #78.

You should try with `"explicitFolding.delay": 0,` but you might have issue with languages which already have a folding provider.
The folding is managed by vscode, the extension can't control which region to fold or not. So, sadly, I can't do a `explicitFolding.saveFoldsInProject`.

I will try to make another PR in vscode to try to fix your issue.

For now, I will close the issue.

**Closed by daiyam** 2022-04-25 08:17 UTC
