### ISSUE TITLE
Version 0.9.1 no longer folds last line.

### ISSUE THREAD

**Issue by michael-lumley** [zokugun/vscode-explicit-folding#30] opened 2020-12-25 17:30 UTC
I was using this extension in VS code as described in this thread. https://github.com/microsoft/vscode/issues/3352. On release of the new version, the extension reverted to leaving the trailing parenthesis/bracket in place. I successfully reverted to 0.9.0 without issue, and don't intend to upgrade to 0.9.1 until the issue is resolved.

**Comment by daiyam** [comment] 2020-12-25 17:58
@michael-lumley Can you give an example with you config? I've changed how the folding ranges are resolved...

**Comment by michael-lumley** [comment] 2020-12-28 11:35
This is from the thread linked above but I confirmed that the below config DOES fold a trailing `}` on 0.9.0 and DOES NOT on 0.9.1. In other words

0.9.0:
![image](https://user-images.githubusercontent.com/8387649/103211704-c79e6f00-48bd-11eb-8b3d-956db71b575f.png)

0.9.1:
![image](https://user-images.githubusercontent.com/8387649/103211696-bf463400-48bd-11eb-9341-a2bf4de80d51.png)

```
"folding": {
    "*": {
        "begin": "{",
        "end": "}"
    },
}
```

**Comment by daiyam** [comment] 2020-12-28 13:44
@michael-lumley It's what I thought. The newest version isn't providing the folding you are seeing but it's another extension.
Can you tell me which language you are using and the extension providing it?

Here what I got with Javascript and the builtin language provider:
![screenshot](https://user-images.githubusercontent.com/587742/103218094-6b1d6d00-491a-11eb-917e-c9ee62038207.png)

**Comment by daiyam** [comment] 2020-12-29 18:33
@michael-lumley hi, I need more infos to investigation the issue because it depends on how VSCode merge the folding ranges from the different providers. So I need the language you are using and the extension which is providing it.
Additionally, in the config, you could test to replace the `*` with your language.

**Comment by daiyam** [comment] 2021-01-13 10:23
@michael-lumley hi, I still need those infos. Can you give them? Thx

**Comment by citeru** [comment] 2021-01-30 18:23
i have the same problem im  using typescript. is there a way to fix it??

**Comment by sleepylemur** [comment] 2021-02-12 20:40
@daiyam Hi, I'm seeing the same issue. Not sure how to check what the currently active folding provider is.
This setting block hides the closing brace on 9.0 but not with 9.1
```
  "folding": {
    "*": {
        "begin": "{",
        "end": "}",
    }
  }
```
I am able to get it to work for just typescript or just javascript files by replacing "*" with "typescript" or "javascript" respectively on 9.0, but I'm unable to get 9.1 to work with either.

**Comment by daiyam** [comment] 2021-02-12 21:29
@sleepylemur I can't reproduce the problem so can you give me an example with the language used ;) Thx

**Comment by sleepylemur** [comment] 2021-02-12 22:08
Example using javascript:
filename: test.js

function happy() {
  console.log("yo");
}

On 9.0 looks like 
<img width="235" alt="image" src="https://user-images.githubusercontent.com/5049698/107827041-fbd9cc00-6d53-11eb-8f4b-950dcb434987.png">

On 9.1 looks like
<img width="233" alt="image" src="https://user-images.githubusercontent.com/5049698/107827198-4f4c1a00-6d54-11eb-8396-fd84ab9024da.png">

Not too familiar with vscode extensions and why mine would work differently than yours. I'll see if I can dig through and debug the issue since reproducing on your end is probably not going to be easy.

Also I'm on macOS 11.2.1

VSCode Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by daiyam** [comment] 2021-02-12 23:31
@sleepylemur Thanks for your info, I was able to reproduce it and I feel pretty stupid... I've misread a `max()` with a `min()`... several times.
I've fixed and published the new version. Tell me if it's working for you. Thx

**Comment by sleepylemur** [comment] 2021-02-12 23:38
@daiyam confirmed that 0.9.2 works for me. Thanks for the extension!

**Comment by daiyam** [comment] 2021-02-12 23:40
Great! Thanks for your help it was bugging me.

**Closed by daiyam** 2021-02-12 23:40 UTC
