### ISSUE TITLE
Code folding 'issue' on autohotkey

### ISSUE THREAD

**Issue by pepeu93** [zokugun/vscode-explicit-folding#64] opened 2021-07-31 19:59 UTC
I'm using the extension to fold the code between `{ }`

But on this example:
            
    Function() {
        
        x = "`{"
        msgbox %x%
     }

The `{` inside the quotes 'break' the folding, i see that this extension support regex, i tried:

```
    "explicitFolding.rules": {
        "ahk": [
            {
                "beginRegex": "{",
                "middleRegex": "",
                "endRegex": "}"
            }
        ]
    }
```
I'm not sure how to ignore these `{` `}` when they are inside quotes using regex, then it doesn't mess up the folding.

Also, any suggestion or tips to solve this 'problem' is welcome. I'm currently using the extension with AutoHotkey.

**Comment by daiyam** [comment] 2021-07-31 20:05
You should escape the quotes like so:
```
[
 {
    "begin": "\"",
    "end": "\"",
    "nested": false
  },
  {
    "begin": "{",
    "end": "}"
  }
]
```

**Comment by pepeu93** [comment] 2021-07-31 20:17
Hi thank you for answering, but it still does match it:
![image](https://user-images.githubusercontent.com/82878129/127751511-7919f8bf-4c28-4288-98fb-2925a6c02c64.png)

**Comment by daiyam** [comment] 2021-07-31 20:26
It's working on my test. Can you add the debug (`"explicitFolding.debug": true`) and give the log.

**Comment by pepeu93** [comment] 2021-07-31 20:27
Sorry but where do i get the log?

**Comment by daiyam** [comment] 2021-07-31 20:30
I should get the following regex: `regex: /(?<_3_0>")|(?<_0_1>\{)|(?<_2_1>\})/g`
I don't see the `(?<_3_0>")` in your regex.

**Comment by pepeu93** [comment] 2021-07-31 20:30
![image](https://user-images.githubusercontent.com/82878129/127751799-6768cdb9-7143-454c-a31a-1e25d276f71c.png)
this is my settings.json

**Comment by daiyam** [comment] 2021-07-31 20:40
Weird... from the log, I can conclude that the config was:
```
[
  {
    "begin": "/*",
    "end": "*/"
  },
  {
    "begin": "{",
    "end": "}"
  }
]
```

Can you provide the following infos:
- VSCode: 
- Explicit Folding: 
- Language: 
- Language Provider:

**Comment by pepeu93** [comment] 2021-07-31 20:51
Now it does work, it was an issue with a previous extension that also fold code and it was really using
`
  {
    "begin": "/*",
    "end": "*/"
  },
`
Thank you so much for the help!!

**Comment by pepeu93** [comment] 2021-07-31 21:06
i have found another problem```
string = :(.*?)"

Function() {

}
``` 
a string without closing quotes make it does not fold anything, if i close the quotes or remove it, it works as expected

**Comment by daiyam** [comment] 2021-08-02 02:09
Based on https://github.com/ahkscript/SublimeAutoHotkey/blob/master/AutoHotkey.tmLanguage, it should be:

```
[
 {
    "beginRegex": "\"",
    "endRegex": "\"(?!\")|^",
    "nested": false
  },
  {
    "begin": "{",
    "end": "}"
  }
]
```

**Comment by daiyam** [comment] 2021-08-15 09:38
@pepeu93 Were you able to test the updated rules?

**Comment by daiyam** [comment] 2021-09-20 10:42
@pepeu93 Can you tell me if the issue have been resolved?

**Comment by ccaioccesar** [comment] 2021-10-04 06:00
@daiyam hi sorry, i don't use Github with frequency, i had no seen your message.

Topic:
No, it doesn't.
For example:
```
				if (output1 != "") 
				{
					regex2   = i)\/\*%key%\*\/[\/*-]+%output1%\*\/[0-9]
					Len     := StrLen(value)
					Len     -= %output1%
					replace  = /*%key%*//*R*//*-%output1%*/%Len%

					File 	   := RegexReplace(File,regex2,replace)	

				} 
```In this code, it does match both `{` `}`.

**Comment by daiyam** [comment] 2021-10-04 07:28
@ccaioccesar new account?

Anyway, I've tested and the configuration I've given you is invalid.
But the example you've given me, doesn't have the issue shown in the image.
Can you send me the whole file?

Here a validated config:
```
  "[ahk]": {
    "explicitFolding.debug": true,
    "explicitFolding.rules": [
      {
        "beginRegex": "\"(?:(?:[^\"]|\\\")*)(?=\")",
        "endRegex": "\""
      },
      {
        "begin": "{",
        "end": "}"
      }
    ]
  },
```

**Comment by ccaioccesar** [comment] 2021-10-04 07:40
@daiyam I had lost the password of that other account.

With this new config, everything is working correctly.
Thank you Daiyam!👍

**Comment by daiyam** [comment] 2021-10-04 08:39
Ya, comment blocks can be tricky.

The following config will allow to fold most comment blocks:
```
  "[ahk]": {
    "explicitFolding.debug": true,
    "explicitFolding.rules": [
      {
        "kind": "comment",
        "begin": "^\\s*\/*",
        "end": "*\/",
        "nested": false
      },
      {
        "beginRegex": "\"(?:(?:[^\"]|\\\")*)(?=\")",
        "endRegex": "\""
      },
      {
        "begin": "{",
        "end": "}"
      }
    ]
  },
```

**Comment by ccaioccesar** [comment] 2021-10-04 09:03
Looks like it did not work?
Also, break some folding in other scripts.
Debug:

```
[document] lang: ahk, fileName: Untitled-1
[main] regex: /(?<_0_0>\^\\s\*\/\*)|(?<_0_1>"(?:(?:[^"]|\")*)(?="))|(?<_2_1>")|(?<_0_2>\{)|(?<_2_2>\})/g
[document] foldings: []
```


![image](https://user-images.githubusercontent.com/73500606/135823557-c43e436b-3b2c-4fa0-9ce4-7a9f5e6c6b4e.png)

**Comment by daiyam** [comment] 2021-10-04 09:28
Stupid me! It needs to be regex...

```
  "[ahk]": {
    "explicitFolding.debug": true,
    "explicitFolding.rules": [
      {
        "kind": "comment",
        "beginRegex": "^\\s*\\/\\*",
        "endRegex": "\\*\\/",
        "nested": false
      },
      {
        "beginRegex": "\"(?:(?:[^\"]|\\\")*)(?=\")",
        "endRegex": "\""
      },
      {
        "begin": "{",
        "end": "}"
      }
    ]
  },
```

**Comment by R3uan3** [comment] 2022-04-05 18:17
Hello @daiyam
I'm also trying to use your extension with `AutoHotkey`, however, when I re-open vscode it unfolds `everything`.
You can reproduce this issue by just folding a function closing vscode and opening it again, then the function will be unfolded.

**Comment by daiyam** [comment] 2022-04-05 18:53
@R3uan3 Yes, it's the default behaviour of vscode (as far I know). This is why I've added the property [`explicitFolding.autoFold`](https://github.com/zokugun/vscode-explicit-folding#auto-fold). But it might be different from what you want.

**Comment by R3uan3** [comment] 2022-04-05 19:37
`explicitFolding.autoFold` just folds everything, I was trying to find a way to keep the folding the same way it was before reopening.

When I change the option in folding strategy from auto to indentation and reopen vscode, it does remember which functions were folded and which weren't.
However, this type of folding is very weird as it folds empty lines and things outside brackets :/

 
![image](https://user-images.githubusercontent.com/103058225/161835172-d82abd6f-45d5-4f7f-aba2-d8c405169907.png)

**Comment by daiyam** [comment] 2022-04-05 19:57
@R3uan3 I will look into it.
By the way, does the previously given config is working correctly?

**Comment by R3uan3** [comment] 2022-04-05 20:00
Yes, it does!

**Comment by R3uan3** [comment] 2022-04-11 22:21
@daiyam hello did you find something? its sad when i restart my computer and reopen vscode it mess with all folding and from the place I left the caret on :(

**Comment by daiyam** [comment] 2022-04-12 04:19
No, I haven't look at it yet.

**Comment by daiyam** [comment] 2022-04-14 19:59
I'm closing this issue since the rules are working.

**Closed by daiyam** 2022-04-14 19:59 UTC
